export const FETCH_GIVERS_REQUEST = 'FETCH_GIVERS_REQUEST'
export const FETCH_GIVERS_SUCCESS = 'FETCH_GIVERS_SUCCESS'
export const FETCH_GIVERS_FAILURE = 'FETCH_GIVERS_FAILURE'

export const ADD_GIVER_REQUEST = 'ADD_GIVER_REQUEST'
export const ADD_GIVER_SUCCESS = 'ADD_GIVER_SUCCESS'
export const ADD_GIVER_FAILURE = 'ADD_GIVER_FAILURE'

export const SET_ACTIVE_GIVER = 'SET_ACTIVE_GIVER'

export const REMOVE_GIVER_SUCCESS = 'REMOVE_GIVER_SUCCESS'
export const REMOVE_GIVER_FAILURE = 'REMOVE_GIVER_FAILURE'
