export const UPLOAD_FILES_REQUEST = 'UPLOAD_FILES_REQUEST'
export const UPLOAD_FILES_SUCCESS = 'UPLOAD_FILES_SUCCESS'
export const UPLOAD_FILES_FAILURE = 'UPLOAD_FILES_FAILURE'

export const DOWNLOAD_FILES_REQUEST = 'DOWNLOAD_FILES_REQUEST'
export const DOWNLOAD_FILES_SUCCESS = 'DOWNLOAD_FILES_SUCCESS'
export const DOWNLOAD_FILES_FAILURE = 'DOWNLOAD_FILES_FAILURE'