export const FETCH_TAKERS_REQUEST = 'FETCH_TAKERS_REQUEST'
export const FETCH_TAKERS_SUCCESS = 'FETCH_TAKERS_SUCCESS'
export const FETCH_TAKERS_FAILURE = 'FETCH_TAKERS_FAILURE'

export const ADD_TAKER_REQUEST = 'ADD_TAKER_REQUEST'
export const ADD_TAKER_SUCCESS = 'ADD_TAKER_SUCCESS'
export const ADD_TAKER_FAILURE = 'ADD_TAKER_FAILURE'

export const STOP_DONATE_TAKER = 'STOP_DONATE_TAKER'

export const REMOVE_TAKER_SUCCESS = 'REMOVE_TAKER_SUCCESS'
export const REMOVE_TAKER_FAILURE = 'REMOVE_TAKER_FAILURE'

export const DONATE_TAKER_REQUEST = 'DONATE_TAKER_REQUEST'
export const DONATE_TAKER_SUCCESS = 'DONATE_TAKER_SUCCESS'
export const DONATE_TAKER_FAILURE = 'DONATE_TAKER_FAILURE'

export const UPDATE_DONATE_REQUEST = 'UPDATE_DONATE_REQUEST'
export const UPDATE_DONATE_SUCCESS = 'UPDATE_DONATE_SUCCESS'
export const UPDATE_DONATE_FAILURE = 'UPDATE_DONATE_FAILURE'

export const REMOVE_DONATE_SUCCESS = 'REMOVE_DONATE_SUCCESS'
export const REMOVE_DONATE_FAILURE = 'REMOVE_DONATE_FAILURE'
