"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

from dotenv import load_dotenv
import os
from backend.utils.credentials import credentials_manager

load_dotenv()  # Load variables in .env file into environment

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
SETTINGS_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE_DIR = os.path.dirname(SETTINGS_DIR)
MEDIA_URL = 'images/'

# Load credentials from JSON file
try:
    # Cloudinary configuration
    CLOUDINARY_CONFIG = credentials_manager.get_cloudinary_config()
    CLOUDINARY_CLOUD_NAME = CLOUDINARY_CONFIG['cloud_name']
    CLOUDINARY_API_KEY = CLOUDINARY_CONFIG['api_key']
    CLOUDINARY_API_SECRET = CLOUDINARY_CONFIG['api_secret']
    
    # Google Drive configuration
    GOOGLE_DRIVE_CONFIG = credentials_manager.get_google_drive_config()
    SERVICE_ACCOUNT_FILE = credentials_manager.credentials_file
    SCOPES = GOOGLE_DRIVE_CONFIG.get('scopes', ['https://www.googleapis.com/auth/drive'])
    DRIVEFOLDERID = GOOGLE_DRIVE_CONFIG.get('folder_id', '1oFoOJg9fVsdtHkyfQS2Vph0asGDe1Sg2')
    
    # Storage configuration
    STORAGE_CONFIG = credentials_manager.get_storage_config()
    STORAGE = STORAGE_CONFIG.get('type', 'Cloudinary')
    print(f"Storage: {STORAGE}")
except FileNotFoundError:
    print("Credentials file not found")
    # Fallback to environment variables if credentials file doesn't exist
    CLOUDINARY_CLOUD_NAME = os.getenv('CLOUDINARY_CLOUD_NAME', 'your_cloudinary_cloud_name')
    CLOUDINARY_API_KEY = os.getenv('CLOUDINARY_API_KEY', 'your_cloudinary_api_key')
    CLOUDINARY_API_SECRET = os.getenv('CLOUDINARY_API_SECRET', 'your_cloudinary_api_secret')
    
    SERVICE_ACCOUNT_FILE = os.path.join(BASE_DIR, 'credentials.json')
    SCOPES = ['https://www.googleapis.com/auth/drive']
    DRIVEFOLDERID = '1oFoOJg9fVsdtHkyfQS2Vph0asGDe1Sg2'
    STORAGE = 'Cloudinary'


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# Django configuration
try:
    DJANGO_CONFIG = credentials_manager.get_django_config()
    SECRET_KEY = DJANGO_CONFIG['secret_key']
    DEBUG = DJANGO_CONFIG['debug']
    ALLOWED_HOSTS = DJANGO_CONFIG['allowed_hosts']
except FileNotFoundError:
    # Fallback to environment variables if credentials file doesn't exist
    SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'verybadsecret!!!')
    DEBUG = os.getenv('DJANGO_DEBUG', 'true').lower() == 'true'
    ALLOWED_HOSTS = os.getenv('DJANGO_ALLOWED_HOSTS', '*').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'whitenoise.runserver_nostatic',  # < Per Whitenoise, to disable built in
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'coreapi',
    'backend.api',
    'backend.takers',
]

REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.coreapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        # 'rest_framework.permissions.AllowAny',
        # 'rest_framework.permissions.IsAuthenticated',
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'EXCEPTION_HANDLER': 'backend.exception_handler.global_exception_handler'
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Add dist to
        # 'DIRS': ['dist'],
        'DIRS': ['public'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

# Database configuration
try:
    DB_CONFIG = credentials_manager.get_database_config()
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'HOST': DB_CONFIG['host'],
            'PORT': DB_CONFIG['port'],
            'NAME': DB_CONFIG['name'],
            'USER': DB_CONFIG['user'],
            'PASSWORD': DB_CONFIG['password']
        }
    }
except FileNotFoundError:
    # Fallback to environment variables if credentials file doesn't exist
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '5432'),
            'NAME': os.getenv('DB_NAME', 'giveandtake'),
            'USER': os.getenv('DB_USER', 'giveandtake'),
            'PASSWORD': os.getenv('DB_PASSWORD', 'giveandtake')
        }
    }


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

# When Vue Builds, path will be `/static/css/...` so we will have Django Serve
# In Production, it's recommended use an alternative approach such as:
# http://whitenoise.evans.io/en/stable/django.html?highlight=django

MIDDLEWARE_CLASSES = (
    'whitenoise.middleware.WhiteNoiseMiddleware',
)

STATIC_URL = '/static/'
# Place static in the same location as webpack build files
# STATIC_ROOT = os.path.join(BASE_DIR, 'dist', 'static')
STATIC_ROOT = os.path.join(BASE_DIR, 'public', 'static')
STATICFILES_DIRS = []


##########
# STATIC #
##########

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Insert Whitenoise Middleware at top but below Security Middleware
# MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware',)
# http://whitenoise.evans.io/en/stable/django.html#make-sure-staticfiles-is-configured-correctly
