name: Keep Alive

on:
  workflow_dispatch:       # allow manual run
  schedule:
    - cron: '*/15 * * * *' # run random every 15m


concurrency:
  group: keep-alive
  cancel-in-progress: true # cancel the last job if start the new job


jobs:
  ping:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
    steps:
      - name: Install dependencies
        run: |
          apk add --no-cache bash curl

      - name: Ping Server with Random Delay
        shell: bash
        run: |
          URLS=(
            "https://giveandtake-api.onrender.com/docs"
            "https://giveandtake.onrender.com"
          )

          # Max retries for each ping
          MAX_RETRIES=3

          # Loop through each URL
          for url in "${URLS[@]}"
          do
            # Log the current URL
            echo "Pinging $url..."

            # Generate random delay (8 to 12 minutes)
            RANDOM_DELAY=$(( RANDOM % 241 + 480 ))
            sleep $RANDOM_DELAY

            ATTEMPT=1
            SUCCESS=false

            while [ $ATTEMPT -le $MAX_RETRIES ]
            do
              STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" "$url")
              if [ "$STATUS_CODE" -eq 200 ]; then
                echo "Ping $url success!"
                SUCCESS=true
                break
              else
                echo "Ping $url failed (attempt $ATTEMPT)"
                ((ATTEMPT++))
                sleep 10
              fi
            done

            if [ "$SUCCESS" = false ]; then
              echo "Ping failed $url after $MAX_RETRIES attempts."
            fi
          done