name: Keep Alive

on:
  workflow_dispatch:       # allow manual run
  schedule:
    - cron: '*/15 * * * *' # run random every 15m


concurrency:
  group: keep-alive
  cancel-in-progress: true # cancel the last job if start the new job


jobs:
  ping:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
    steps:
      - name: Ping Server with Random Delay
        run: |
          URLS=(
            "https://giveandtake-api.onrender.com/docs"
            "https://giveandtake.onrender.com"
          )

          MAX_RETRIES=3

          for url in "${URLS[@]}"
          do
            RANDOM_DELAY=$(( RANDOM % 241 + 480 )) # random delay from 8m to 12m
            sleep $RANDOM_DELAY
            ATTEMPT=1
            SUCCESS=false

            while [ $ATTEMPT -le $MAX_RETRIES ]
            do
              STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" $URL)
              if [ "$STATUS_CODE" -eq 200 ]; then
                echo "Ping $url success!"
                SUCCESS=true
                break
              else
                echo "Ping $url failed (timer $ATTEMPT)"
                ((ATTEMPT++))
                sleep 10
              fi
            done

            if [ "$SUCCESS" = false ]; then
              echo "❌ Ping failed $URL after $MAX_RETRIES times."
            fi
          done